package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRating<M extends BaseRating<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUserId(java.lang.Integer userId) {
		set("userId", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public M setBookId(java.lang.Long bookId) {
		set("bookId", bookId);
		return (M)this;
	}
	
	public java.lang.Long getBookId() {
		return getLong("bookId");
	}

	public M setRating(java.lang.Integer rating) {
		set("rating", rating);
		return (M)this;
	}
	
	public java.lang.Integer getRating() {
		return getInt("rating");
	}

	public M setUserName(java.lang.String userName) {
		set("userName", userName);
		return (M)this;
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

}
