package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProxyAdd<M extends BaseProxyAdd<M>> extends Model<M> implements IBean {

	public M setHost(java.lang.String host) {
		set("host", host);
		return (M)this;
	}
	
	public java.lang.String getHost() {
		return getStr("host");
	}

	public M setPort(java.lang.Integer port) {
		set("port", port);
		return (M)this;
	}
	
	public java.lang.Integer getPort() {
		return getInt("port");
	}

	public M setFlag(java.lang.Integer flag) {
		set("flag", flag);
		return (M)this;
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setTotal(java.lang.Integer total) {
		set("total", total);
		return (M)this;
	}
	
	public java.lang.Integer getTotal() {
		return getInt("total");
	}

	public M setErrorInfo(java.lang.String errorInfo) {
		set("error_info", errorInfo);
		return (M)this;
	}
	
	public java.lang.String getErrorInfo() {
		return getStr("error_info");
	}

}
