package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRating<M extends BaseRating<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setUser(java.lang.String user) {
		set("user", user);
		return (M)this;
	}
	
	public java.lang.String getUser() {
		return getStr("user");
	}

	public M setBookId(java.lang.Long bookId) {
		set("bookId", bookId);
		return (M)this;
	}
	
	public java.lang.Long getBookId() {
		return getLong("bookId");
	}

	public M setRating(java.lang.Integer rating) {
		set("rating", rating);
		return (M)this;
	}
	
	public java.lang.Integer getRating() {
		return getInt("rating");
	}

}
