package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("book", "id", Book.class);
		arp.addMapping("book_json", "id", BookJson.class);
		arp.addMapping("proxy_add", "host", ProxyAdd.class);
		arp.addMapping("rating", "id", Rating.class);
		arp.addMapping("tag", "id", Tag.class);
	}
}

