package com.demo.common.model;

import com.demo.common.model.base.BaseBookJson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookJson extends BaseBookJson<BookJson> {
	public static final BookJson dao = new BookJson().dao();
}
