package com.demo.common.model;

import com.demo.common.model.base.BaseBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Book extends BaseBook<Book> {
	public static final Book dao = new Book().dao();

	public static  long id = 1005993l;

    public Book getOneBook() {
        synchronized(this){
        Book book =  dao.findFirst("select * from book where flag=0 limit 1");
//        id=book.getId();
        return book;
        }

    }
}
