package com.demo.common.model;

import com.demo.common.model.base.BaseBook;
import com.jfinal.plugin.cron4j.Cron4jPlugin;

import java.util.LinkedList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Book extends BaseBook<Book> {
	public static final Book dao = new Book().dao();

	public static List<Book> list = new LinkedList<>();



    public Book getOneBook() {
        synchronized(this){
            if (list.size()==0){
                list = dao.find("select * from book where flag=0 limit 4000");
            }
            if (list.size()==0){
                new Cron4jPlugin().stop();
                return null;
            }
            Book book = list.remove(0);
            return book;


//        Book book =  dao.findFirst("select * from book where flag=0 limit 1");
//        id=book.getId();
//        return book;
        }
    }


    /**
     * 获取基本的图书信息，id，书名，作者，标签
     * @param bookId
     * @return
     */
    public Book getBaseInfo(Object bookId){
        return dao.findByIdLoadColumns(bookId, " id, title, author, tags, translator");
    }


}
