package com.demo.common.model;

import com.demo.common.model.base.BaseRating;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rating extends BaseRating<Rating> {
	public static final Rating dao = new Rating().dao();
}
